spring:
  datasource:
    url: 'jdbc:postgresql://fhir_db:5432/fhir'
    username: fhir
    password: example
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: false